### PR TITLE
Change character table

### PR DESCRIPTION
**Pull request by SlaveMast3r**
Added Configuration class to make change character table and encoding available. Made like non-breaking feature.

### CODE REVIEW

**Comment by DantSu** [comment]
Hi thx for this PR,
Can you explain me, how user change char encoding ?

**Comment by SlaveMast3r** [comment]
To not break current solution and make it easy, I created new static class `EscPosPrinterConfig` which will contains printer configuration. There you can anytime setup own character table (number known from self test) and desired encoding. Default values stayed same to not make new problems.

Configuration options are called before each print run.

//set before printing to change character table and charset encoding
EscPosPrinterConfig.CHARACTER_TABLE = 0x06; //Western Europe 
EscPosPrinterConfig.CHARSET_ENCODING = "ISO-8859-1";

**Comment by SlaveMast3r** [comment]
Example to setup Windows-1250.

EscPosPrinterConfig.CHARACTER_TABLE = 72; //windows-1250 character table
EscPosPrinterConfig.CHARSET_ENCODING = "Cp1250"; //windows-1250 encoding

**Comment by DantSu** [comment]
Ok, so I understood the idea.
For me, this is not a correct solution. Developers should not enter the library code to change the encoding. Everything must be done on the application side. I will commit an update this afternoom.

**Comment by DantSu** [comment]
Hi, I just added charset encoding in v1.0.1. Thx for your report and PR.

**Pull request closed without merging**
