### PR TITLE
Adding example in Kotlin

### PR DESCRIPTION
**Pull request by SnorSnor9998**

### CODE REVIEW

**Comment by DantSu** [comment]
I don't want to add Kotlin example. The README file becomes too big and confusing.

**Comment by shahinnawas** [comment]
Unresolved reference: UsbPrintersConnections in kotlin
@SnorSnor9998

**Comment by SnorSnor9998** [comment]
Sorry cant test it for you because i don't have USB printer in hand

**Comment by shahinnawas** [comment]
it was fixed when downgrading dependency to 2.0.10, Thank you for your time 
@SnorSnor9998

**Pull request closed without merging**
