### PR TITLE
Throw 3 exceptions: parsing, encoding and connection

### PR DESCRIPTION
**Pull request by steamerstudio**
I added 3 exceptions related to parsing, encoding or connection errors.
Many files have changed but on a very limited aspects.

Please check and let me know.

### CODE REVIEW

**Comment by DantSu** [comment]
Thx for this PR, I will check that tomorrow.

**Comment by DantSu** [comment]
First read, seems to be a good job,

In MainActivity : 
```java
            try {
                this.printIt(BluetoothPrintersConnections.selectFirstPaired());
            } catch(BrokenConnectionException | ParserException | EscPosEncodingException e) {
                e.printStackTrace();
            }
```
Put this inside print it, because it's duplicate code.

```java
               try {
                    TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
                    printIt(tcpConnection);
                } catch (Exception e) {
                    e.printStackTrace();
                }
```

This `(Exception e)` is too generic, I do a bad job. It's a `NumberFormatException`.

```java
        if (barcodeAttributes.containsKey(PrinterTextParser.ATTR_BARCODE_HEIGHT)) {
            String barCodeAttribute = barcodeAttributes.get(PrinterTextParser.ATTR_BARCODE_HEIGHT);
            if (barCodeAttribute == null)
                throw new ParserException("Invalid barcode attribute: height");
            this.height = printer.mmToPx(Float.parseFloat(barcodeAttributes.get(PrinterTextParser.ATTR_BARCODE_HEIGHT)));
        }
```
`NumberFormatException` to `ParserException("Invalid barcode attribute: height")`

**Comment by steamerstudio** [comment]
Agreed. Thanks. I performed the changes.

**Comment by steamerstudio** [comment]
Hi, could you merge this PR ? Or do you expect additional changes ?
Thanks.

**Comment by DantSu** [comment]
I did not have enought time to review.

**Comment by steamerstudio** [comment]
No worries :)

**Pull request merged**
